### ISSUE TITLE
Source Code Quality - Architecture and Tests

### ISSUE THREAD

**Issue by afronski** [Appliscale/cftool#19]
We're missing couple of points regarding code quality - let's address most important ones in `1.0` release.

- As we did not know anything about road-map, we couldn't plan structure and architecture of this project. Now we know more and it is time to prepare more modular structure (more packages? Preparing places for a library that could be extracted?).
- Lack of unit tests. We need those. 😉 
- We are not measuring code coverage (there is no goal for _CC_, but we can enable it in the build pipeline).
- We can leverage rest of `go` tooling - e.g. `go vet` and other stuff (_static code analysis_) and include it in the build pipeline.
- Reviewing dependencies and preparing a list with rationale "_why we chose them_" (_Wiki_).

**Comment by pfigwer** [comment]
Nice article about Go test coverage https://blog.golang.org/cover 😃

**Comment by pfigwer** [comment]
I will create documentation with godoc for 1.0 release
