### ISSUE TITLE
Basic Offline Validation

### ISSUE THREAD

**Issue by afronski** [Appliscale/cftool#4]
Currently we have online validation based on _AWS API_, which is usual one, but far from ideal.

Issues with current approach:

- Occurrence of first failure causes bail out.
- It needs internet connectivity.
- It provides just basic validation, most of the errors could be avoided after introducing more complicated validators (e.g. which are aware of the field type).

In the first milestone we need:

- Multiple syntax validation errors for _JSON_ (if possible to parse) and showing place where is it.
- Multiple syntax validation errors for _YAML_ (if possible to parse) and showing place where is it.
- Offline validation for _CloudFormation_ resources based on _AWS CloudFormation Resource Specificaion_, from [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html).
  - If that will be too much work - **we can prioritize** most important resources that should land in `1.0`.
  - Again - multiple validation errors (if possible to parse).
  - What should we validate?
    - Values provided as a base types (_Number_, _String_, _Boolean_).
    - Presence of _Type_ annotations.
  - This task should built a foundation that will allow to monitor more complicated types (e.g. _IP_, _CIDR_ etc.).
    - Still, we don't want to built a _DSL_ / _plug-in_ here system yet.

Remember to use that _YAML_ / _JSON_ validation also when converting between those.

And we need to document a list of validation checks and how to use such command on our _Wiki_ or inside _README_ file.

**Comment by pfigwer** [comment]
AWS CloudFormation Resource Specification parser is almost ready. There is just one more thing to do before specification will be ready to use in validation - serving AWS specification file to the application. Specification files are identical for almost all regions, except few that contains a resource specification for AWS CodeCommit. I think for now we can use just one resource file for the application and later, if needed, we can add support for using separate specification per region.

I've found a nice tool for embedding files into a go program - [go-bindata](https://github.com/jteeuwen/go-bindata). That way our validator could be completely offline 😃

**Comment by afronski** [comment]
@pfigwer We can also download it and cache in user's home directory.

**Comment by pfigwer** [comment]
I thought about it. Example URL looks like this: https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json. But I cannot find any information if domain name may change in time.

**Comment by afronski** [comment]
It may change - as the _CloudFront_ distribution (hash at the beginning will change). Let's do this way:

- We can store prefix `https://d1uauaxba7bl26.cloudfront.net/latest/gzip` as a setting in the machine global configuration file (`/etc/` stated in #5) - if necessary someone will change it, and we can deliver it inside our distribution with proper default too.

And when it comes to comparison - I'd rather calculate checksum (e.g. `sha256`) and compare those, but you've probably thought about it too. ;)

**Comment by pfigwer** [comment]
@afronski I'm starting to write some mechanism for adding resource type aware validators. Do you have any suggestions from which resources we should start our implementation?
