### ISSUE TITLE
Multi-Level Configuration - Base

### ISSUE THREAD

**Issue by afronski** [Appliscale/cftool#5]
Currently - as we're using official _AWS SDK_ for _Go_ - we should properly leverage `~/.aws` configuration - including profiles, defaults (e.g. default region for profile or CLI rendering) and credentials management.

However from our experience that's not entirely enough, especially if you are switching between profiles. What I would like to propose is to add additional configuration layer for our tool based on typical hierarchical configuration that is in line with _UNIX filesystem_ (overrides go from top to the bottom of following list):

- Machine global configuration in `/etc/`.
- User specific configuration in `~/.[name]` or `~/.config/[name]`.
- Project directory (_root_ of the project, e.g. where `.git` resides) with project specific configuration file called `.[name]`.
  - **Q**: should we / how to do resolution, if someone calls the tool not from the root of the project?

For now we should have there only 2 configuration fields:

- `profile` - pointing on _AWS CLI_ profile used by default.
- `region` - pointing, overriding default region used by _AWS CLI_.

After developing - it needs proper _documentation_ section for setting it up correctly.

**Comment by pfigwer** [comment]
TODO: Add cross-platform support.

**Comment by pfigwer** [comment]
@morfeush22 will handle cross-platform support :)

**Comment by morfeush22** [comment]
As now, I think we can agree that configuration files location pattern on Unix systems is right.

I want to propose comparable pattern on Windows (basing on https://technet.microsoft.com/pl-pl/library/cc749104(v=ws.10).aspx):
1. User local config
`CSIDL_LOCAL_APPDATA ` + `cftool/main.yaml`

To quote:

> The file system directory that serves as a data repository for local (nonroaming) applications. A typical path is C:\Documents and Settings\username\Local Settings\Application Data.
2. Global system config
`CSIDL_COMMON_APPDATA` + `cftool/main.yaml`

> Version 5.0. The file system directory containing application data for all users. A typical path is C:\Documents and Settings\All Users\Application Data.

**Comment by afronski** [comment]
:+1: Very good finding, if you will have problem with a leading `.` (for `.cftool`) on _Windows_ - we can replace it by `_`.
